std = "roblox+luau"

[lints]
unused_variable     = "allow"  # Selene stays quiet; Luau still reports if you want it
unscoped_variables  = "deny"   # forbid accidental globals
shadowing           = "warn"

# Exclude vendored Wally packages to avoid duplicate/ noisy diagnostics
exclude = [
  "Packages/**",
  "ServerPackages/**",
  "DevPackages/**",
]
