indent_type = "Spaces"
indent_width = 2
column_width = 120
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

# Roblox/Luau compatibility for Stylua >= 0.18
syntax = "Luau"
