[package]
name = "jsm91/games"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4.0.0"
Networker = "leifstout/networker@0.3.0"
Loader = "sleitnick/loader@2.0.0"
Fusion = "elttob/fusion@^0.3"
Flipper = "reselim/flipper@^2"
Janitor = "howmanysmall/janitor@^1.18.3"
t = "osyrisrblx/t@^3"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
DataService = "leifstout/dataservice@0.3.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerScriptService.ServerPackages"
